"use strict";
function renderCommerceV4(s,body,tab){
 if(tab==='payments'){
  const gateways=s.gateways||{};
  body.innerHTML=`<section class="panel sale-card payment-hero"><span class="mini-label">ARIA PAYMENTS / 04</span><h2>پرداخت، تأیید، تحویل.</h2><p>مشتری پلن را انتخاب می‌کند؛ پس از تأیید تراکنش توسط درگاه، سرویس یا اعتبار کیف پول خودکار تحویل می‌شود. تمام قیمت‌ها تومان‌اند و برای درگاه به ریال تبدیل می‌شوند.</p><div class="commerce-flow"><span>۱ · انتخاب پلن</span><span>۲ · پرداخت بانکی</span><span>۳ · تأیید سرور</span><span>۴ · کانفیگ آماده</span></div></section><form id="gateway-settings-form"><div class="sale-duo">${[['zarinpal','زرین‌پال','ZARINPAL'],['zibal','زیبال','ZIBAL']].map(([id,label,en])=>`<section class="panel sale-card"><span class="mini-label">${en} / DIRECT</span><h3>${label}</h3><p>${gateways[id]?.configured?'✓ مرچنت ذخیره شده است. برای حفظ آن کادر را خالی بگذار.':'مرچنت رسمی حساب درگاه خودت را وارد کن.'}</p><label class="toggle-line"><input type="checkbox" name="${id}Enabled" ${gateways[id]?.enabled?'checked':''}>فعال‌کردن این درگاه</label>${field(id+'Merchant','مرچنت خصوصی','','password','autocomplete="new-password" dir="ltr" maxlength="128"')}<p class="field-note">مرچنت در API عمومی یا بکاپ فروش قرار نمی‌گیرد. سرویس به callback مرورگر اعتماد نمی‌کند و تأیید را از سرور درگاه می‌گیرد.</p></section>`).join('')}</div><div class="sale-actions"><button type="submit" class="button primary">ذخیرهٔ درگاه‌ها</button></div></form><section class="panel sale-card"><h3>قبل از اولین فروش</h3><p>دامنه عمومی HTTPS باید آماده باشد. آدرس بازگشت برای هر سفارش خودکار ساخته می‌شود. در حساب درگاه، دامنه همین پنل را ثبت کن. حداقل مبلغ قابل پرداخت ۱۰۰۰ تومان است. ابتدا یک خرید با مبلغ کم از حساب خودت آزمایش کن.</p><p>پرداخت کارت‌به‌کارت به بررسی رسید توسط مدیر نیاز دارد؛ شماره کارت، حساب و شبا را در «تنظیمات فروش» وارد کن. نتیجهٔ نامشخص درگاه را دوباره پرداخت نکن؛ از «بررسی پرداخت» استفاده کن.</p></section>`;
  return true;
 }
 if(tab==='bot'){
  const t=s.settings, tg=state?.telegram||{}, available=(state?.profiles||[]).filter(p=>p.available!==false);
  body.innerHTML=`<div class="sale-duo bot-duo"><section class="panel sale-card"><span class="mini-label">TELEGRAM / CONVERSATION</span><h2>ربات فروش خودت.</h2><p>${tg.enabled?'✓ ربات فعال است. مشتری /start را می‌زند و با دکمه‌ها خرید می‌کند.':'توکن ربات و شناسهٔ مدیر را در تنظیمات اتصال تلگرام وارد و ربات را فعال کن.'}</p><form id="bot-studio-form"><label>متن خوش‌آمد<textarea name="welcome" rows="4" maxlength="1200">${esc(t.welcome||'')}</textarea></label><label class="toggle-line"><input name="reminderEnabled" type="checkbox" ${t.reminderEnabled?'checked':''}>یادآوری مصرف حجم و پایان اعتبار</label><hr><h3>سرویس تست · یک بار برای هر حساب تلگرام</h3><label class="toggle-line"><input name="trialEnabled" type="checkbox" ${t.trialEnabled?'checked':''}>فعال‌کردن تست اتصال روی همین پنل</label><div class="form-grid">${field('trialQuotaGB','حجم تست / GB',t.trialQuotaGB||0.2,'number','min="0.01" max="5" step="0.01"')}${field('trialDays','اعتبار / روز',t.trialDays||1,'number','min="1" max="7"')}</div><fieldset><legend>الگوهای تست</legend>${available.map(p=>`<label class="toggle-line"><input type="checkbox" name="trialProfiles" value="${esc(p.key)}" ${(t.trialProfiles||['vless-ws']).includes(p.key)?'checked':''}><span dir="ltr">${esc(p.name)}</span></label>`).join('')}</fieldset><button class="button primary" type="submit">ذخیرهٔ ربات فروش</button></form><p class="field-note">تست روی مقصد محلی ساخته می‌شود؛ برای چند پنل، مقصد هر پلن فروش را جدا تعیین کن. آزمون رایگان به‌معنی جلوگیری کامل از ساخت چند حساب تلگرام نیست.</p></section><section class="panel sale-card bot-preview-panel"><span class="mini-label">CUSTOMER PREVIEW</span><div class="bot-phone"><div class="bot-phone-head"><span class="bot-avatar">A</span><div><b>${esc(t.name)}</b><small>ربات فروش اتصال</small></div></div><div class="bot-bubble"><b>🔥 ${esc(t.name)}</b><p id="bot-welcome-preview">${esc(t.welcome||'به فروشگاه اتصال خوش آمدی. پلن را انتخاب کن، پرداخت کن و کانفیگ آماده بگیر.')}</p><small>💳 کیف پول · کانفیگ آماده · پشتیبانی</small></div><div class="bot-keyboard">${['🛍 خرید سرویس','📦 سرویس‌های من','💳 کیف پول','🧾 سفارش‌ها','🆘 پشتیبانی','🌐 فروشگاه / QR','🎁 تست اتصال','⌂ منوی اصلی'].map(x=>'<span>'+x+'</span>').join('')}</div><div class="bot-bubble subtle"><b>مسیر خرید</b><p>پلن ← تخفیف اختیاری ← روش پرداخت ← تأیید ← اشتراک و فایل کانفیگ</p></div></div><h3>ادامه پس از ری‌استارت</h3><p>سفارش، کیف پول، وضعیت پرداخت و صف ارسال در پوشهٔ داده نگه‌داری می‌شوند. برای حفظ آن‌ها، Volume دائمی و یک Replica لازم است.</p><p>پشتیبانی از پرداخت تومانی، کارت‌به‌کارت، کیف پول و Stars؛ اتصال پنل‌های ariaatashin، 3x-ui و Marzban از «پنل‌های مقصد».</p></section></div>`;
  return true;
 }
 return false;
}
document.addEventListener('input',e=>{if(e.target.form?.id==='bot-studio-form'&&e.target.name==='welcome')$('#bot-welcome-preview').textContent=e.target.value||'به فروشگاه اتصال خوش آمدی.'});
document.addEventListener('submit',e=>{
 if(!['gateway-settings-form','bot-studio-form'].includes(e.target.id))return;
 e.preventDefault();const form=e.target,f=new FormData(form);
 busy($('button[type="submit"]',form),async()=>{
  if(form.id==='gateway-settings-form')await api('/api/sales/gateways',{method:'POST',body:{zarinpal:{enabled:f.has('zarinpalEnabled'),merchant:f.get('zarinpalMerchant')},zibal:{enabled:f.has('zibalEnabled'),merchant:f.get('zibalMerchant')}}});
  else await api('/api/sales/settings',{method:'POST',body:{...commerce.settings,welcome:f.get('welcome'),reminderEnabled:f.has('reminderEnabled'),trialEnabled:f.has('trialEnabled'),trialQuotaGB:+f.get('trialQuotaGB'),trialDays:+f.get('trialDays'),trialProfiles:f.getAll('trialProfiles')}});
  await loadSales();toast('تنظیمات ذخیره شد.');
 }).catch(err=>toast(err.message,true));
});

$('#telegram-discover').addEventListener('click',e=>busy(e.currentTarget,async()=>{const d=await api('/api/telegram/discover',{method:'POST',body:{token:$('#telegram-form [name=token]').value}}),box=$('#telegram-discovery');if(!d.chats?.length){box.textContent='پیامی پیدا نشد؛ در چت همین ربات Start بزن و دوباره تلاش کن.';return}box.innerHTML='<label>حساب خودت را انتخاب کن<select id="telegram-chat-choice"><option value="">انتخاب حساب</option>'+d.chats.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+' · '+esc(c.id)+'</option>').join('')+'</select></label>';$('#telegram-chat-choice').onchange=e=>{$('#telegram-form [name=chatId]').value=e.target.value;toast('شناسه انتخاب شد؛ تنظیمات ربات را ذخیره کن.')}}).catch(err=>toast(err.message,true)));
