"use strict";
const Q=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fa=n=>new Intl.NumberFormat('fa-IR').format(n||0), money=n=>fa(n)+' تومان', date=n=>n?new Date(n).toLocaleDateString('fa-IR'):'بدون انقضا';
let catalog=null,account=null,tab='plans', shopActionBusy=false;
function methodOptions(topup=false){return (catalog.paymentMethods||[{id:"manual",name:"کارت / حساب و رسید"},{id:"wallet",name:"کیف پول"}]).filter(m=>!topup||m.id!=="wallet").map(m=>`<option value="${esc(m.id)}">${esc(m.name)}${m.id==='wallet'?' · '+money(account.customer.balance):''}</option>`).join('')}
async function openGateway(id){const p=await request('orders/'+id+'/pay',{}),u=new URL(p.url);if(u.protocol!=='https:'||!['www.zarinpal.com','gateway.zibal.ir'].includes(u.hostname))throw Error('آدرس درگاه معتبر نیست');location.assign(u.href)}
const statusNames={pending:'در انتظار پرداخت',receipt:'بررسی رسید',paid:'پرداخت‌شده',provisioning:'ساخت سرویس',fulfilled:'تحویل‌شده',uncertain:'بازیابی تحویل',failed:'بررسی مدیر',cancelled:'لغو‌شده'};
async function request(path,body){const headers={'Accept':'application/json','X-Requested-With':'aria-shop','X-ARIA-Origin':location.origin};let data;if(body instanceof FormData)data=body;else if(body!==undefined){headers['Content-Type']='application/json';data=JSON.stringify(body)}const r=await fetch('/shop/api/'+path,{method:body===undefined?'GET':'POST',headers,body:data,credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(45000)});const v=await r.json().catch(()=>({}));if(!r.ok){const e=Error(v.error||'خطای ارتباط با فروشگاه');e.status=r.status;throw e}return v}
function toast(s){const el=document.createElement('div');el.className='toast';el.textContent=s;Q('#shop-toast').replaceChildren(el);setTimeout(()=>el.remove(),6500)}
function btn(label,action,id=''){return `<button class="button secondary" data-act="${action}" data-id="${esc(id)}">${label}</button>`}
function modal(title,content,submit){const d=Q('#shop-dialog');d.innerHTML=`<div class="modal-header"><h2>${esc(title)}</h2><button type="button" class="icon-button" data-close aria-label="بستن">×</button></div><form id="shop-form"><div class="modal-body">${content}<p class="form-error" id="shop-error" role="alert"></p></div><div class="modal-footer">${submit?'<button class="button primary" type="submit">ثبت</button>':''}<button class="button secondary" type="button" data-close>بستن</button></div></form>`;if(!d.open)d.showModal();if(submit)Q('#shop-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type=submit]');b.disabled=true;try{await submit(new FormData(e.currentTarget));d.close();await refresh()}catch(err){Q('#shop-error').textContent=err.message}finally{b.disabled=false}}}
async function refresh(){catalog=await request('catalog');Q('#shop-name').textContent=catalog.settings.name;Q('#shop-support').textContent=catalog.settings.support;try{account=await request('me');Q('#shop-account').hidden=false;Q('#shop-login-note').hidden=true;Q('#shop-customer').textContent=account.customer.name;Q('#shop-balance').textContent=money(account.customer.balance)}catch(err){if(err.status!==401)throw err;account=null;Q('#shop-account').hidden=true;Q('#shop-login-note').hidden=false;tab='plans'}render()}
function render(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const box=Q('#shop-content');if(tab==='plans'){box.innerHTML=`<h2 class="shop-title">پلن مناسب خودت را انتخاب کن.</h2>${catalog.settings.trialEnabled&&account&&account.customer.telegramId>0&&!account.customer.trialOrder?btn("🎁 تست اتصال یک‌بار برای این حساب", "trial"):""}<div class="sale-plan-grid">${catalog.plans.map(p=>`<article class="panel sale-plan"><span class="mini-label">${p.days?fa(p.days)+' روز':'بدون انقضا'} / CONNECTION PLAN</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><strong>${money(p.price)}</strong><ul class="shop-plan-features"><li>✦ ${p.quotaGB?fa(p.quotaGB)+' گیگابایت':'حجم نامحدود'}</li><li>✦ لینک و اشتراک آماده</li><li>✦ ${fa(p.profiles?.length||1)} الگوی انتخاب‌شده</li><li>✦ پشتیبانی در همین فروشگاه</li></ul><button class="button primary wide" data-act="buy" data-id="${esc(p.id)}">انتخاب این پلن ↗</button></article>`).join('')||'<div class="empty-state"><h3>پلن تازه در راه است.</h3><p>فعلاً پلن فعالی برای فروش ثبت نشده است.</p></div>'}</div>`;return}if(!account)return;
if(tab==='services'){box.innerHTML='<div class="shop-service-grid">'+account.services.map(v=>`<article class="panel shop-service"><span class="mini-label">${v.enabled?'SERVICE / ACTIVE':'SERVICE / DISABLED'}</span><h3>${esc(v.name)}</h3><p>مصرف ${fa(v.used/1073741824)} GB / ${v.quota?fa(v.quota/1073741824)+' GB':'نامحدود'}<br>اعتبار تا ${date(v.expiry)}</p><progress max="100" value="${v.quota?Math.min(100,v.used/v.quota*100):0}" aria-label="مصرف"></progress><label>اشتراک<input readonly dir="ltr" value="${esc(v.subscription)}"></label><div class="sale-actions">${btn('کپی اشتراک','copy',v.id)}${btn('لینک / QR','links',v.id)}${btn('همگام‌سازی','sync',v.id)}${btn('تمدید','renew',v.id)}</div></article>`).join('')+'</div>';if(!account.services.length)box.innerHTML='<div class="empty-state"><h3>اولین اتصال را بساز.</h3><p>سرویس پس از تأیید پرداخت اینجا قرار می‌گیرد.</p></div>';return}
if(tab==='orders'){box.innerHTML=account.orders.map(o=>`<article class="panel shop-order"><div><code>${esc(o.id)}</code><h3>${esc(o.kind==='topup'?'شارژ کیف پول':o.plan?.name)}</h3><strong>${o.currency==='XTR'?fa(o.amount)+' Stars':money(o.amount)}</strong><p>${date(o.created)} · ${o.kind==='renew'?'تمدید':o.kind==='buy'?'خرید':'شارژ'}</p><span class="sale-status ${esc(o.status)}">${statusNames[o.status]||'در حال بررسی'}</span>${o.error?'<p>'+esc(o.error)+'</p>':''}</div><div>${o.method==='manual'&&['pending','receipt'].includes(o.status)?btn('ثبت رسید','receipt',o.id):''}${['zarinpal','zibal'].includes(o.method)&&o.status==='pending'?btn('پرداخت درگاه','pay',o.id)+btn('بررسی پرداخت','check',o.id):''}${o.method==='manual'&&['pending','receipt'].includes(o.status)?btn('لغو سفارش','cancel',o.id):''}</div></article>`).join('')||'<div class="empty-state">هنوز سفارشی ثبت نکرده‌ای.</div>';return}
if(tab==='tickets'){box.innerHTML=btn('تیکت تازه','ticket')+account.tickets.slice().reverse().map(t=>`<article class="panel shop-ticket"><small>${date(t.created)} · ${t.reply?'پاسخ داده‌شده':'در انتظار پاسخ'}</small><p>${esc(t.text)}</p>${t.reply?'<blockquote>'+esc(t.reply)+'</blockquote>':''}</article>`).join('');return}}
function orderModal(p,service=''){const key=crypto.randomUUID();modal(service?'تمدید سرویس':'خرید '+p.name,`<div class="sale-order-summary"><h3>${esc(p.name)}</h3><strong>${money(p.price)}</strong><p>${fa(p.quotaGB)} GB · ${fa(p.days)} روز</p></div><label>روش پرداخت<select name="method">${methodOptions()}</select></label><label>کد تخفیف<input name="coupon" maxlength="32"></label><p class="field-note">پرداخت دستی پس از بررسی مدیر تأیید می‌شود.</p>`,async f=>{const o=await request('orders',{kind:service?'renew':'buy',planId:p.id,serviceId:service,method:f.get('method'),coupon:f.get('coupon'),idempotency:key});tab='orders';if(['zarinpal','zibal'].includes(o.method)){await refresh();await openGateway(o.id);return}toast(o.status==='fulfilled'?'سرویس آماده شد.':'سفارش ثبت شد؛ وضعیت را در سفارش‌ها ببین.')})}
async function action(act,id){if(!account){toast('اول فروشگاه را از ربات یا لینک خصوصی مدیر باز کن.');return}if(act==='pay'){await openGateway(id);return}if(act==='check'){await request('orders/'+id+'/check',{});await refresh();toast('پرداخت تأیید شد؛ سفارش در حساب شماست.');return}if(act==='trial'){await request('trial',{});tab='services';await refresh();toast('تست آماده شد.');return}if(act==='buy'){orderModal(catalog.plans.find(p=>p.id===id));return}if(act==='renew'){const v=account.services.find(v=>v.id===id);const plans=catalog.plans.filter(p=>(p.nodeId||'')===(v.nodeId||''));modal('انتخاب پلن تمدید',`<label>پلن<select name="plan">${plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${money(p.price)}</option>`).join('')}</select></label>`,async f=>{const p=plans.find(p=>p.id===f.get('plan'));if(!p)throw Error('پلن تمدید روی همین مقصد موجود نیست');setTimeout(()=>orderModal(p,id),30)});return}
if(act==='copy'){const v=account.services.find(v=>v.id===id);await navigator.clipboard.writeText(v.subscription);toast('کپی شد.');return}if(act==='sync'){await request('services/'+id+'/sync',{});await refresh();toast('وضعیت تازه شد.');return}if(act==='links'){const v=account.services.find(v=>v.id===id);modal('لینک‌های آماده',`<div class="qr-holder" id="shop-qr"></div><label>اشتراک<input readonly dir="ltr" value="${esc(v.subscription)}"></label><label>لینک‌ها<textarea readonly dir="ltr" rows="6">${esc(v.links.join('\n'))}</textarea></label>`);try{const q=qrcode(0,'M');q.addData(v.subscription||v.links[0]);q.make();Q('#shop-qr').innerHTML=q.createSvgTag({cellSize:4,margin:16,scalable:true})}catch{Q('#shop-qr').textContent='لینک را کپی کن.'}return}
if(act==='receipt'){const o=account.orders.find(o=>o.id===id),s=catalog.settings;modal('ثبت رسید پرداخت',`<div class="sale-order-summary"><strong>${money(o.amount)}</strong><p>${esc(s.paymentNote)}</p><code>${esc(s.cardNumber)}</code><p>${esc(s.cardHolder)} · ${esc(s.bankName)}</p><p>حساب: <code>${esc(s.accountNumber)}</code></p><p>شبا: <code>${esc(s.iban)}</code></p></div><label>شمارهٔ پیگیری / توضیح<input name="receipt" maxlength="1000"></label><label>عکس رسید؛ JPEG / PNG، حداکثر ۴ MB<input type="file" name="photo" accept="image/png,image/jpeg"></label>`,async f=>{const photo=f.get('photo');if(photo?.size>4*1024*1024)throw Error('عکس باید کمتر از ۴ مگابایت باشد');await request('orders/'+id+'/receipt',f);toast('رسید ثبت شد؛ منتظر تأیید مدیر بمان.')});return}
if(act==='cancel'){modal('لغو سفارش','<p>این سفارش لغو شود؟</p>',async()=>{await request('orders/'+id+'/cancel',{});toast('لغو شد.')});return}if(act==='ticket'){modal('پشتیبانی',`<label>پیام<textarea name="text" rows="5" required minlength="3" maxlength="2000"></textarea></label>`,async f=>{await request('tickets',{text:f.get('text')});toast('تیکت ثبت شد.')});return}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))Q('#shop-dialog').close();if(b.dataset.tab){tab=b.dataset.tab;render()}if(b.dataset.act&&!shopActionBusy){shopActionBusy=true;b.disabled=true;action(b.dataset.act,b.dataset.id).catch(err=>toast(err.message)).finally(()=>{shopActionBusy=false;b.disabled=false})}});
Q('#shop-refresh').onclick=()=>refresh().catch(e=>toast(e.message));Q('#shop-topup').onclick=()=>{const key=crypto.randomUUID();modal('شارژ کیف پول',`<label>مبلغ تومان<input type="number" name="amount" min="1000" max="1000000000" required></label><label>روش پرداخت<select name="method">${methodOptions(true)}</select></label><p>اعتبار پس از تأیید درگاه یا بررسی رسید افزوده می‌شود.</p>`,async f=>{const o=await request('orders',{kind:'topup',method:f.get('method'),amount:+f.get('amount'),idempotency:key});tab='orders';if(['zarinpal','zibal'].includes(o.method)){await refresh();await openGateway(o.id);return}toast('سفارش شارژ ثبت شد؛ رسید را در سفارش‌ها بفرست.')})};
(async()=>{try{const access=new URLSearchParams(location.hash.slice(1)).get('access');if(access){history.replaceState(null,'',location.pathname);await request('login',{access})}else{const initData=window.Telegram?.WebApp?.initData;if(initData){window.Telegram.WebApp.ready();await request('login',{initData})}}await refresh()}catch(e){toast(e.message);Q('#shop-login-note').hidden=false;Q('#shop-login-note span').textContent=e.message;try{await refresh()}catch{}}})();
